### ISSUE TITLE
No green light

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/ttt-4-display-board-rb#19]
There's no green light for the last lesson I completed under Methods called "Display Tic Tac Toe Board". Maybe it's supposed to be like that? It's just bothering me...

**Comment by AnnJohn** [comment]
Hi @dfaulring this looks like its a bug. Could you please submit a bug report (if you hover over your profile pic in Learn, you'll see an option for Report a Bug). For immediate help you can also use the Ask a Question tool in Learn and someone from our support team will help you out. Thanks!
