### ISSUE TITLE
ArgumentError:  wrong number of arguments (0 for 1)

### ISSUE THREAD

**Issue by ilmam** [learn-co-curriculum/ttt-4-display-board-rb#27]
Sorry if this sounds a silly question. I am new to Learn platform and trying to get used to it.

I am trying to run the test for this lab.
The code for `display_board.rb` is as follows:

```
def display_board(board)
  puts " #{board[0]} | #{board[1]} | #{board[2]} "
  puts "-----------"
  puts " #{board[3]} | #{board[4]} | #{board[5]} "
  puts "-----------"
  puts " #{board[6]} | #{board[7]} | #{board[8]} "
end

board = [" "," "," "," "," "," "," "," "," "]
display_board(board)

```

When I run `rspec --fail-fast` I get the following output:

```

/lib/display_board.rb
  defines a method display_board
  #display_board method
    represents a cell as a string with 3 spaces (FAILED - 1) 

Failures: 

  1) /lib/display_board.rb #display_board method represents a cell as a string with 3 spaces

     Failure/Error:
       def display_board(board)
         puts " #{board[0]} | #{board[1]} | #{board[2]} "
         puts "-----------"
         puts " #{board[3]} | #{board[4]} | #{board[5]} "
         puts "-----------"
         puts " #{board[6]} | #{board[7]} | #{board[8]} "
       end

     ArgumentError:
       wrong number of arguments (0 for 1)
     # ./lib/display_board.rb:2:in `display_board'
     # ./spec/display_board_spec.rb:10:in `block (4 levels) in <top (required)>' 
     # ./spec/spec_helper.rb:5:in `capture_puts'
     # ./spec/display_board_spec.rb:10:in `block (3 levels) in <top (required)>'

Finished in 0.00296 seconds (files took 0.14604 seconds to load)

2 examples, 1 failure

Failed examples:

rspec ./spec/display_board_spec.rb:9 # /lib/display_board.rb #display_board method represents a cell as a string with 3 spaces
```

I don't get why I am getting this error: "wrong number of arguments (0 for 1)"

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by ilmam** [comment]
I included in the question the output error. How can I include the stack trace?

**Comment by ilmam** [comment]
Any help here?

**Comment by ilmam** [comment]
Issue resolved. Thanks.
