### ISSUE TITLE
lab requirements

### ISSUE THREAD

**Issue by pahosler** [learn-co-curriculum/ttt-4-display-board-rb#29]
In this lab, as well as many others, the code requirements are too vague. This particular lab even throws in a red herring, suggesting that you go back to the previous display_board lab to recall how to display the board. That particular lab required output in the format:
 "   |   |   \n-----------\n   |   |   \n-----------\n   |   |   \n"
using that format, here's my code for the new lab...

def display_board(board)
  players = ""
    board.each_with_index do |x,index|
    players += ((x == "" ? "   " : " " + x + " ")+(2 > index%3 ? "|" : index <8 ? "\n-----------\n":"\n"))
  end
  players
end

This is simple code that produces the desired output, is very easy to test, and creates a string similar to the first display_board lab. It also removes a level of complexity by not creating more arrays, again making it easier to test while at the same time keeping it useful as a function that has only one purpose... display the board. This lab is expecting an array of rows, i.e. row[0], row[1], etc. This would be more clear if the array passed to display_row was formatted as: 

display_row( [ ["X","X","X"],["O","O","O"],["X","O","X"] ] ) 

This would make the lab slightly more difficult but the tests would essentially be the same except now testing, row[0,0], row[0,1], etc. However, to me, it seems like testing for a string

" X | X | X \n-----------\n   O | O | O \n-----------\n X | O | X \n"

would be easier than testing multiple arrays.

**Comment by gj** [comment]
Hi @pahosler !

While it's awesome that you were able to come up with your own solution (keep doing that! 🙂), I think we'll stick with the current setup (based off of the previous `#display_board` lab). In my eyes...
```ruby
def display_board(board)
  puts " #{board[0]} | #{board[1]} | #{board[2]} "
  puts "-----------"
  puts " #{board[3]} | #{board[4]} | #{board[5]} "
  puts "-----------"
  puts " #{board[6]} | #{board[7]} | #{board[8]} "
end
```
...is easier to read than:
```ruby
def display_board(board)
  players = ""
  board.each_with_index do |x,index|
    players += ((x == "" ? " " : " " + x + " ")+(2 > index%3 ? "|" : index <8 ? "\n-----------\n":"\n"))
  end
  players
end
```

Thanks!
