### ISSUE TITLE
Another Option?

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/ttt-4-display-board-rb#31]
Hey, while I understand the desired code for this lesson is something along these lines... 
```
def display_board(board = " ")
  
puts " #{board[0]} | #{board[1]} | #{board[2]} "
puts "-----------"
puts " #{board[3]} | #{board[4]} | #{board[5]} "
puts "-----------"
puts " #{board[6]} | #{board[7]} | #{board[8]} "
end

display_board(board = [" ", " ", " ", " ", "X", " ", " ", " ", " "])
display_board(board = ["O", " ", " ", " ", " ", " ", " ", " ", " "])
display_board(board = ["O", " ", " ", " ", "X", " ", " ", " ", " "])
```

...is there a reason the following is not also suitable? 

```
# Board with X in center

#Empty board
def display_board(board = " ")
board = [" ", " ", " ", " ", " ", " ", " ", " ", " "]

# X/O Input
board[4] = "X"

#Board
puts " #{board[0]} | #{board[1]} | #{board[2]} "
puts "-----------"
puts " #{board[3]} | #{board[4]} | #{board[5]} "
puts "-----------"
puts " #{board[6]} | #{board[7]} | #{board[8]} "
end

display_board
```
If this is an acceptable answer, it may be beneficial to include it as passable in the "learn" function.

**Comment by drakeltheryuujin** [comment]
Hi there, thank you for your feedback! 

It looks like this isn't a bug in the curriculum, but a misunderstanding you have with the material. That's no problem though! If you are having difficulty understanding why this logic would not be an accepted answer, go ahead and hit the Ask A Question button on [learn.co](http://learn.co). Either a community member or a technical coach will be able to help you understand this stuff. 

Good luck! 💙
