### ISSUE TITLE
tests are getting false positives because it is expecting output to include

### ISSUE THREAD

**Issue by snags88** [learn-co-curriculum/ttt-4-display-board-rb#6]
A student pointed this out, but if you run

``` ruby
board = ["X", "X", "X", "X", "O", "X", "X", "X", "X"] 
output = capture_puts{ display_board(board) } if defined?(display_board)

expect(output).to include(" X | X | X ")
expect(output).to include("-----------")
expect(output).to include(" X | X | X ")
expect(output).to include("-----------")
expect(output).to include(" X | X | X ")
```

you'll get a false positive because the tests are just checking to see if those lines appear in the output. The output looks like `" X | X | X \n--------\n X | O | X \n--------\n X | X | X \n"`.

**Comment by AnnJohn** [comment]
@aturkewi the specs might have changed after this issue was raised. if so, feel free to close this issue.
