### ISSUE TITLE
My code pass the test, but it looks not right

### ISSUE THREAD

**Issue by cocacolabe** [learn-co-curriculum/ttt-4-display-board-rb#7]
board = [" "," "," "," "," "," "," "," "," "]
def display_board(board)

```
  puts " #{board[0]} | #{board[1]} | #{board[2]} "
  puts "-----------"
  puts " #{board[3]} | #{board[4]} | #{board[5]} "
  puts "-----------"
  puts " #{board[6]} | #{board[7]} | #{board[8]} "
```

  end

**Comment by AnnJohn** [comment]
Hi @cocacolabe  for raising this issue. SInce this looks like something you'd like immediate feedback, please use the "Ask a Question" tool in Learn. Someone from our instructor support staff will get back to you right away.
