### ISSUE TITLE
All tests passing in terminal but "local build" icon still red

### ISSUE THREAD

**Issue by eaylward8** [learn-co-curriculum/ttt-4-display-board-rb#8]
For this lab, my code is passing all tests when I run `learn` in the terminal.  

I submitted with `learn submit`.

Everything seems okay, but the lab page's Local Build icon is still red.  Note, I do have access to the next lesson, so it's not preventing me from moving forward.

**Comment by AnnJohn** [comment]
Hi @eaylward8 this looks like it's an engineering bug. For immediate help with the problem, please use the "Ask a Question" tool in Learn and someone will help you right away.

**Comment by eaylward8** [comment]
Hey @AnnJohn, thanks for replying.  No immediate help needed, just wanted to raise the issue.

**Comment by AnnJohn** [comment]
Ok, great!
